name: DevSecOps Demo

on:
  push:
    branches:
      - main

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update App Version
      run: |
        NEW_VERSION="v$(date +'%Y%m%d%H%M%S')"
        echo $NEW_VERSION > VERSION.txt
        git config user.name "Demo Bot"
        git config user.email "demo@example.com"
        git add VERSION.txt
        git commit -m "Update app version to $NEW_VERSION"
        git push || echo "No changes to commit"

    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        image: demo-app:${{ github.sha }}

    - name: Scan for secrets
      uses: gacts/gitleaks@v1
      with:
        version: v8.x

    - name: Build Docker image
      run: docker build -t demo-app:${{ github.sha }} .

    - name: Sign container image
      run: |
        cosign generate-key-pair || echo "Keys already exist"
        cosign sign --key cosign.key demo-app:${{ github.sha }}

    - name: OPA policy check
      run: |
        echo 'package main
        deny[msg] { input.secrets != "" ; msg = "Secrets found in repo" }' > policy.rego
        echo '{"secrets": ""}' > input.json
        opa eval --data policy.rego --input input.json "data.main.deny"
